import LegalLayout, { H2, H3, P, UL } from './LegalLayout'
import { LEGAL_ENTITY, CONTACT_EMAIL } from './version'

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy">
      <P>
        This Privacy Policy describes how <strong>{LEGAL_ENTITY}</strong> ("we", "us") collects,
        uses, stores, and shares information when you use UGC OS (the "Service").
      </P>

      <H2>1. What we collect</H2>
      <H3>Information you provide</H3>
      <UL>
        <li><strong>Account data</strong> — email address, password (stored hashed by Supabase Auth), display name.</li>
        <li><strong>API keys</strong> — your kie.ai Bearer key. Stored in your <code>profiles</code> row and used to call kie.ai directly from your browser.</li>
        <li><strong>Inputs</strong> — prompts, scripts, products, character profiles, reference images, audio.</li>
        <li><strong>Outputs</strong> — generated images, videos, voiceovers, and music produced by the Service on your behalf.</li>
      </UL>

      <H3>Information collected automatically</H3>
      <UL>
        <li>Authentication session tokens (managed by Supabase).</li>
        <li>Server logs (IP, user-agent, timestamps) generated by our hosting providers.</li>
        <li>Local browser storage (localStorage, IndexedDB) used to cache banks, settings, and asset blobs on your device.</li>
      </UL>

      <H2>2. How we use your information</H2>
      <UL>
        <li>To provide, operate, and improve the Service.</li>
        <li>To authenticate you and enforce the community access list.</li>
        <li>To route AI requests on your behalf through kie.ai and the underlying model providers.</li>
        <li>To store your banks, history, and assets so they persist across sessions and devices.</li>
        <li>To respond to support requests and enforce our Terms and Acceptable Use Policy.</li>
      </UL>

      <H2>3. Subprocessors and data sharing</H2>
      <P>
        We do not sell your personal data. We share data with the following service providers
        solely to operate the Service:
      </P>
      <UL>
        <li><strong>Supabase</strong> — authentication and Postgres database (account, profile, banks, history rows).</li>
        <li><strong>Cloudflare R2</strong> — object storage for generated images, videos, audio.</li>
        <li><strong>Vercel</strong> — application hosting and edge functions (presigned-URL signing).</li>
        <li><strong>kie.ai</strong> — unified API gateway for AI model calls. Your prompts, reference images, and any other input data you submit for generation are sent from your browser to kie.ai.</li>
        <li>
          <strong>Downstream AI providers via kie.ai</strong> — including OpenAI, Google
          (Gemini, Veo), ElevenLabs, Suno, and others. Your inputs may be processed by these
          providers to produce outputs. Each provider has its own privacy practices; refer to
          theirs for details.
        </li>
        <li>
          <strong>Skool / Zapier</strong> — community membership status is synced to our
          allowlist via Zapier. Email is shared for the purpose of access control.
        </li>
      </UL>

      <H2>4. Retention</H2>
      <UL>
        <li>Account and profile data — retained while your account is active and for a reasonable period after deletion to comply with legal obligations.</li>
        <li>Generated assets — retained in Cloudflare R2 until you delete them or your account is closed.</li>
        <li>Video / image / music history rows — retained per the in-app retention windows (e.g., video history is auto-pruned after 14 days).</li>
        <li>Server logs — retained for a limited period as determined by our hosting providers.</li>
      </UL>

      <H2>5. Your rights</H2>
      <P>
        Depending on your jurisdiction (GDPR, UK GDPR, CCPA/CPRA, and similar laws), you may
        have the right to access, correct, delete, port, or restrict processing of your personal
        data, and to object to processing or withdraw consent. To exercise these rights, email{' '}
        <a className="text-zinc-100 underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </P>

      <H2>6. Cookies &amp; local storage</H2>
      <P>
        We use first-party browser storage (localStorage, IndexedDB) to keep the app responsive
        and to cache your banks and assets locally. We do not use third-party advertising
        cookies. Authentication uses Supabase-managed cookies / tokens.
      </P>

      <H2>7. Security</H2>
      <P>
        We use industry-standard measures including TLS in transit, scoped presigned URLs for
        asset access (5-minute lifetime, per-user prefix), Row-Level Security on all database
        tables, and a separate JWT verification step on signed-URL minting. No system is
        perfectly secure; you use the Service at your own risk.
      </P>

      <H2>8. International transfers</H2>
      <P>
        Our subprocessors operate in multiple jurisdictions, including the United States and
        the European Union. By using the Service you understand that your data may be
        transferred across borders.
      </P>

      <H2>9. Children</H2>
      <P>
        The Service is not directed to anyone under 18. We do not knowingly collect data from
        children.
      </P>

      <H2>10. Changes</H2>
      <P>
        We will update this Privacy Policy as the Service evolves. Material changes will be
        notified in-app and require re-acceptance.
      </P>

      <H2>11. Contact</H2>
      <P>
        Privacy questions or requests: <a className="text-zinc-100 underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </P>
    </LegalLayout>
  )
}
