import LegalLayout, { H2, P } from './LegalLayout'
import { LEGAL_ENTITY, LEGAL_JURISDICTION, CONTACT_EMAIL } from './version'

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service">
      <P>
        These Terms of Service ("Terms") govern your access to and use of UGC OS (the "Service"),
        operated by <strong>{LEGAL_ENTITY}</strong> ("we", "us", or "our"). By creating an
        account or using the Service, you agree to be bound by these Terms. If you do not agree,
        do not use the Service.
      </P>

      <H2>1. Eligibility &amp; Accounts</H2>
      <P>
        You must be at least 18 years old and legally capable of entering a binding contract to
        use the Service. Access is gated to members of the associated community; your account
        may be disabled if your community membership ends. You are responsible for maintaining
        the confidentiality of your credentials and for all activity under your account.
      </P>

      <H2>2. The Service</H2>
      <P>
        UGC OS is a browser-based workspace that orchestrates third-party AI models for image,
        video, voice, music, and text generation. AI calls are routed through kie.ai using a
        Bearer API key that <em>you</em> supply. Outputs are generated by upstream providers
        (including OpenAI, Google, ElevenLabs, Suno, and others) and may be subject to those
        providers' own terms.
      </P>

      <H2>3. Your Content &amp; License</H2>
      <P>
        You retain ownership of inputs you provide (prompts, reference images, scripts) and of
        outputs generated using the Service, to the extent permitted by applicable law and by
        the underlying model providers' terms. You grant us a worldwide, non-exclusive,
        royalty-free license to host, store, transmit, and display your inputs and outputs
        solely as necessary to operate the Service for you.
      </P>
      <P>
        You represent and warrant that you have all rights necessary to submit your inputs and
        to use the outputs as you do.
      </P>

      <H2>4. Acceptable Use</H2>
      <P>
        Your use of the Service is also governed by our Acceptable Use Policy, which is
        incorporated into these Terms by reference. Violations may result in suspension or
        termination without refund.
      </P>

      <H2>5. AI Outputs — No Warranty</H2>
      <P>
        AI-generated content can be inaccurate, biased, offensive, or infringing. Outputs are
        provided "as is". You are solely responsible for reviewing, editing, and verifying any
        output before publishing, distributing, or relying on it. Do not use outputs in
        contexts requiring professional, legal, medical, or financial accuracy without
        independent verification.
      </P>

      <H2>6. Third-Party Services &amp; API Keys</H2>
      <P>
        Your kie.ai Bearer key is sent directly from your browser to kie.ai; we do not proxy or
        retain it server-side beyond what is needed to sync your account profile. You are
        responsible for the cost of credits consumed against your kie.ai account and for
        compliance with kie.ai's and downstream providers' terms.
      </P>

      <H2>7. Fees</H2>
      <P>
        Access to the Service is typically bundled with a paid community membership operated on
        a third-party platform. Billing for membership is handled by that platform, not by us.
        Any direct fees we charge will be disclosed before purchase.
      </P>

      <H2>8. Termination</H2>
      <P>
        We may suspend or terminate your account at any time for breach of these Terms, for
        violations of the Acceptable Use Policy, or if your community membership ends. You may
        stop using the Service at any time; deletion of stored content can be requested at{' '}
        <a className="text-zinc-100 underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </P>

      <H2>9. Disclaimer of Warranties</H2>
      <P>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTIES OF ANY KIND,
        EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, NON-INFRINGEMENT, ACCURACY, AND UNINTERRUPTED OPERATION. WE DO NOT WARRANT
        THAT OUTPUTS WILL BE ERROR-FREE, NON-INFRINGING, OR FIT FOR ANY USE.
      </P>

      <H2>10. Limitation of Liability</H2>
      <P>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE BE LIABLE FOR INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, OR FOR LOST PROFITS, REVENUES,
        OR DATA, ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL AGGREGATE LIABILITY FOR ANY
        CLAIMS RELATED TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID
        US DIRECTLY IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR (B) US$100.
      </P>

      <H2>11. Indemnification</H2>
      <P>
        You agree to indemnify, defend, and hold harmless {LEGAL_ENTITY}, its affiliates, and
        their officers, employees, and agents from and against any claims, damages, losses, and
        expenses (including reasonable attorneys' fees) arising out of (a) your inputs or
        outputs, (b) your use of the Service, or (c) your violation of these Terms or
        applicable law.
      </P>

      <H2>12. Governing Law &amp; Dispute Resolution</H2>
      <P>
        These Terms are governed by the laws of {LEGAL_JURISDICTION}, without regard to
        conflict-of-laws principles. Any dispute arising under these Terms will be resolved in
        the courts located in that jurisdiction, unless mandatory consumer-protection law in
        your country of residence requires otherwise.
      </P>

      <H2>13. Changes</H2>
      <P>
        We may update these Terms from time to time. Material changes will be notified in-app;
        continued use after the change constitutes acceptance.
      </P>

      <H2>14. Contact</H2>
      <P>
        Questions about these Terms: <a className="text-zinc-100 underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </P>
    </LegalLayout>
  )
}
